sudo: required
dist: focal
language: node_js
node_js:
  - "14.0"

services:
  - docker

addons:
  chrome: stable

apt:
  sources:
    - google-chrome
  packages:
    - dpkg
    - google-chrome-stable

before_script:
  - npm install
  - sudo apt install -y make python build-essential

script:
  - ng test
  - ng e2e

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ng build --prod;
    docker login -u _ -p $heroku_key registry.heroku.com;
    docker build -t registry.heroku.com/todo-angular-app/web .;
    docker push registry.heroku.com/todo-angular-app/web;
    fi

